### PR TITLE
Update to Bedrock 1.18

### PR DESCRIPTION
**Pull request by kmpoppe**
Updated Protocol parts as per @Camotoy 's a555c23518a564bf2def84c9f9de4cefaa37ce71 to the Protocol repo.
I wonder if that's enought to make BC 1.18 ready?

### CODE REVIEW

**Review by Camotoy — APPROVED** [review]
Should be enough, but I would definitely try connecting using 1.18.0.27 Bedrock if you have a moment. I can test later too.

**Comment by kmpoppe** [comment]
I'm currently lacking the proper environment to try that (working mobile), so I'm not of much use on that front. If you can test that I'd be glad :-)

**Comment by kmpoppe** [comment]
Have now built a new Snapshot with my changes an will Test with the 1.18.10 Beta I have for my phone later today

**Comment by Camotoy** [comment]
The 1.18.10 beta will not be the 1.18 release tomorrow in all likelihood, and it is not the same protocol version as the one the Protocol dependency supports.

**Comment by kmpoppe** [comment]
Guess I'll try to force my W10 edition to be 1.18.0.27 then...

**Comment by kmpoppe** [comment]
If only the app would successfully get a WU token (MCMrARM/mc-w10-version-launcher#153) ;-) 
Guess I'll check if I can debug and see what's really going on.

**Comment by kmpoppe** [comment]
> If only the app would successfully get a WU token ([MCMrARM/mc-w10-version-launcher#153](https://github.com/MCMrARM/mc-w10-version-launcher/issues/153)) ;-) Guess I'll check if I can debug and see what's really going on.

Nope, not able to get it to work

**Comment by kmpoppe** [comment]
It's alive! Well, at least my freshly updated Switch 1.18.0 connects perfectly to my dev version with the changes in this PR, I guess we can consider this a successful test @Pugmatt  :)

**Pull request merged**
