### PR TITLE
Add Public Status Page for all public instances

### PR DESCRIPTION
**Pull request by Xavierhorwood**

### CODE REVIEW

**Comment by LazyBirb** [comment]
There's one question tho, which ports are being checked if they're open? Just the BedrockConnect instance, DNS or both? The idea in general seems good tho

**Comment by Pugmatt** [comment]
Good idea 👍 Thanks for setting that up

**Comment by LazyBirb** [comment]
> If this does work out I will give access to everyone who is currently hosting a Instance the login so they can manage and schedule maintenance on their instances

Sounds good to me

**Comment by LazyBirb** [comment]
Tried it out, got internal server error

`Oops! Something went wrong. For more information contact your server administrator.
Request ID: 4c05f359-8d48-4b68-b788-0dd9913d3ce6`

**Comment by LazyBirb** [comment]
And im able to log in, thank you for hosting this!

**Comment by LazyBirb** [comment]
Suggestion: Grouping the status to their Maintainer

**Comment by LazyBirb** [comment]
Oh yea, it looks more sorted now

**Comment by LazyBirb** [comment]
> > Suggestion: Grouping the status to their Maintainer eg. The group being called "IP of instance (Name of maintainer)" and in there being the instance and if present, the DNS server
> 
> i have given two examples what one do you think would be better

so far the 2nd one looks better

**Comment by LazyBirb** [comment]
Oh yeah this does look good, thanks again

**Pull request merged**
