### PR TITLE
Add support for global custom servers

### PR DESCRIPTION
**Pull request by Technoguyfication**
This adds support for global custom servers, so a server owner hosting the serverlist server can automatically put their server in the list. Custom servers are defined in a JSON file using this format:
```json
[
	{
		"name": "My Custom Server 1",
		"iconUrl": "https://i.imgur.com/3BmFZRE.png",
		"address": "mc1.example.com",
		"port": 19132
	},
	{
		"name": "My Custom Server 2",
		"iconUrl": "https://i.imgur.com/3BmFZRE.png",
		"address": "mc2.example.com",
		"port": 19132
	}
]
```

This file can be specified to the program with the `custom_servers` argument. For example:
`java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true custom_servers=servers.json`

### CODE REVIEW

**Comment by Technoguyfication** [comment]
Closes #41

**Comment by Technoguyfication** [comment]
Here's what it looks like in the browser on a client:
image

**Comment by Pugmatt** [comment]
Looks great! 👍 Thanks for taking the time to implement this. Merging this now.

**Comment by kmpoppe** [comment]
@Technoguyfication @Pugmatt I literally compiled the serverlist server myself JUST to add my custom servers up top ... Thanks for taking the time to adding this :-)

**Pull request merged**
