### PR TITLE
Add My Bedrock Server List

### PR DESCRIPTION
**Pull request by darkmoi3108**

### CODE REVIEW

**Comment by Pugmatt** [comment]
Sorry, this request somehow past my radar. Is your instance still up?

**Comment by dalmatheo** [comment]
Hey. Idk why but you're public dns dosn't work on switch after 1.17 update. Can you fix the thing please ?

**Comment by Pugmatt** [comment]
> Hey. Idk why but you're public dns dosn't work on switch after 1.17 update. Can you fix the thing please ?

https://github.com/Pugmatt/BedrockConnect/issues/196

**Comment by darkmoi3108** [comment]
My bedrock instance is UP and work, can you add this to list ?

**Pull request merged**
